gui:
  language: "en"
git:
  #pagers:
  #  - pager: delta --paging=never --side-by-side
  #    colorArg: always
  pagers:
    - colorArg: always
      pager: delta --paging=never --side-by-side
keybinding:
  universal:
    quit: q #sample
